---
- name: Convert Bash Script to Ansible Playbook
  hosts: scorestack
  become: yes
  tasks: 
    - name: Read hosts file
      ansible.builtin.set_fact:
        hosts_file: "{{ lookup('file', '../hosts')}} "
    - name: Write to hosts file
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: "{{ hosts_file }}" 

    - name: Copy checks folder to remote
      ansible.builtin.copy:
        src: ./checks
        dest: /scorestack/dynamicbeat/
        owner: root
        group: root
        mode: '0755'
        directory_mode: yes

    - name: Setup Dynamicbeat checks
      shell: ./dynamicbeat setup checks checks/
      args:
        chdir: /scorestack/dynamicbeat/

    - name: Run Dynamicbeat checks
      shell: ./dynamicbeat run checks
      args:
        chdir: /scorestack/dynamicbeat/