---
- name: Convert Bash Script to Ansible Playbook
  hosts: scorestack
  become: yes
  tasks: 
    - name: Read hosts file
      ansible.builtin.set_fact:
        hosts_file: "{{ lookup('file', '../hosts')}} "
    - name: Write to hosts file
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: "{{ hosts_file }}" 

    - file:
        path: /scorestack/dynamicbeat/checks
        state: directory
        mode: '0755'  # Sets the permissions for the directory
        recurse: yes

    - name: Create web HTTP checks
      template:
        src: web-app.j2  # Path to your Jinja2 template
        dest: "/scorestack/dynamicbeat/checks/web-app-{{ item }}.json"  # Destination path and file name including the index
        variable_start_string: "||"
        variable_end_string: "||"
      loop: "{{ range(0, 10) }}"

    - name: Create web SSH checks
      template:
        src: web-ssh.j2  # Path to your Jinja2 template
        dest: "/scorestack/dynamicbeat/checks/web-ssh-{{ item }}.json"  # Destination path and file name including the index
        variable_start_string: "||"
        variable_end_string: "||"
      loop: "{{ range(0, 10) }}"   

    - name: Create db MySQL checks
      template:
        src: db-mysql.j2  # Path to your Jinja2 template
        dest: "/scorestack/dynamicbeat/checks/db-mysql-{{ item }}.json"  # Destination path and file name including the index
        variable_start_string: "||"
        variable_end_string: "||"
      loop: "{{ range(0, 10) }}"

    - name: Create db SSH checks
      template:
        src: db-ssh.j2  # Path to your Jinja2 template
        dest: "/scorestack/dynamicbeat/checks/db-ssh-{{ item }}.json"  # Destination path and file name including the index
        variable_start_string: "||"
        variable_end_string: "||"
      loop: "{{ range(0, 10) }}"

    - name: Setup Dynamicbeat checks
      shell: ./dynamicbeat setup checks checks/
      args:
        chdir: /scorestack/dynamicbeat/

    - name: Run Dynamicbeat checks
      shell: ./dynamicbeat run checks
      args:
        chdir: /scorestack/dynamicbeat/