---
- name: Update ScoreStack hosts file
  hosts: scorestack
  become: yes
  gather_facts: no
  tasks: 
    - name: Read hosts file
      ansible.builtin.set_fact:
        hosts_file: "{{ lookup('file', '../hosts')}} "
    - name: Write to hosts file
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: "{{ hosts_file }}" 