- name: Convert Bash Script to Ansible Playbook
  hosts: scorestack
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - git
        state: present

    - name: Clone Scorestack repository
      git:
        repo: 'https://github.com/scorestack/scorestack.git'
        dest: /scorestack
        clone: yes
        update: yes

    - name: Set vm.max_map_count
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes

    - name: Stop Docker Compose
      docker_compose:
        project_src: /scorestack/deployment/small/docker
        files:
          - docker-compose.yml
        state: absent

    - name: Start Docker Compose
      docker_compose:
        project_src: /scorestack/deployment/small/docker
        files:
          - docker-compose.yml
        state: present

    - name: Copy over Dynamicbeat
      copy:
        src: ./dynamicbeat
        dest: /scorestack/dynamicbeat/dynamicbeat
        mode: '0777'

    - name: Setup Dynamicbeat
      shell: ./dynamicbeat setup
      args:
        chdir: /scorestack/dynamicbeat/