---
- name: Deploy the web scrimmage box
  hosts: web*
  vars:
    password: "{{ 'Plink0P@ssw0rd' | password_hash('sha512') }}"
    users:
      - plinko
      - redteam
      - alice
      - bob
      - charlie
      - ccdc
      - david
      - eve
      - frank
      - grace
      - helen
  become: True

  tasks:
  - name: Install dependecies
    ansible.builtin.apt:
      name: "{{ packages }}"
      update_cache: yes
      state: present
    vars:
      packages:
        - apache2
        - php
        - php-fpm
        - php-mysqlnd
        - php-gd
        - php-cli
        - php-curl
        - php-mbstring
        - php-bcmath
        - php-zip
        - php-xml
        - php-json
        - php-intl
        - unzip
        - wget
        - tar

  - name: Download WordPress latest version
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/wordpress.tar.gz

  - name: Unarchive files
    ansible.builtin.unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /var/www/html/
      remote_src: yes

  - name: Set permissions on /var/www/
    ansible.builtin.file:
      path: /var/www/
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

  - name: Remove index.html
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent

  - name: Extract integer X from hostname
    set_fact:
      host_integer: "{{ ansible_hostname | regex_search('([0-9]+)') | first }}"

  - name: Construct db hostname
    set_fact:
      db_hostname: "db{{ host_integer }}"

  - name: Get db IP
    set_fact:
      db_ip: "{{ hostvars[db_hostname]['ansible_host'] }}"

  - name: Point web root to wordpress
    ansible.builtin.lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: "DocumentRoot .*"
      line: "DocumentRoot /var/www/html/wordpress"

  - name: Make wp-config
    ansible.builtin.copy:
      src: /var/www/html/wordpress/wp-config-sample.php
      dest: /var/www/html/wordpress/wp-config.php
      owner: www-data
      group: www-data
      force: no
      remote_src: yes

  - name: Make WordPress point to correct database
    ansible.builtin.lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'DB_HOST'
      line: "define('DB_HOST', '{{db_ip}}');"
      backrefs: yes

  - ansible.builtin.lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'DB_USER'
      line: "define('DB_USER', 'wordpress');"

  - ansible.builtin.lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'DB_PASSWORD'
      line: "define('DB_PASSWORD', 'wordpress');"

  - ansible.builtin.lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'DB_NAME'
      line: "define('DB_NAME', 'wordpress');"

  - ansible.builtin.lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'WP_DEBUG'
      line: "define('WP_DEBUG', true );"

  - ansible.builtin.lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'WP_SITEURL'
      line: "define('WP_SITEURL','http://{{ ansible_ssh_host }}');"

  - ansible.builtin.lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'WP_HOME'
      line: "define('WP_HOME','http://{{ ansible_ssh_host }}');"

  - name: Restart Apache
    service:
      name: apache2
      enabled: true
      state: restarted
